// ============================================================================
// Generator: reads `.scratch/vendor_starter.json` (wiki research output) and
// emits `src/lib/vendorStarter.ts` with the typed dataset.
//
// Criteria for inclusion (validated upstream during the wiki research):
//   - Shop has NO entry requirement (no quest gate, no skill gate, no minigame).
//   - Item has NO requirement to wield (no skill/quest req listed on wiki).
//   - Item passes `isCombatViable` from src/lib/equipmentFilter.ts (cuts
//     skirts, capes-with-zero-stats, eye patches, joke aprons).
//
// Re-run: `npx jest VendorStarterGen`.
// ============================================================================

import fs from 'fs';
import path from 'path';
import { describe, test } from '@jest/globals';
import { EquipmentPiece } from '@/types/Player';
import { isCombatViable } from '@/lib/equipmentFilter';
import eqJson from '../../cdn/json/equipment.json';

const equipment = eqJson as EquipmentPiece[];

// =====
// Item-name fixups: wiki-name → (equipment.json name, version)
// Two cases where the wiki name doesn't drop straight into the dump.
// =====
const NAME_FIX: Record<string, { name: string; version?: string }> = {
  'Priest gown|bottom': { name: 'Priest gown (bottom)', version: '' },
  'Priest gown|top': { name: 'Priest gown (top)', version: '' },
};

// =====
// Items where the wiki name maps to multiple version variants in the dump
// (e.g. poisoned vs unpoisoned). We always want the canonical/unpoisoned
// "raw from vendor" variant.
// =====
const PREFERRED_VERSION_FOR: Record<string, string> = {
  'Bronze dagger': 'Unpoisoned',
  'Iron dagger': 'Unpoisoned',
  'Bronze arrow': 'Unpoisoned',
  'Bronze bolts': 'Unpoisoned',
};

function findEquip(name: string, version: string): EquipmentPiece | null {
  const fixed = NAME_FIX[`${name}|${version}`];
  if (fixed) {
    const hit = equipment.find((e) => e.name === fixed.name && e.version === (fixed.version ?? ''));
    return hit ?? null;
  }
  // explicit version match
  if (version) {
    const hit = equipment.find((e) => e.name === name && e.version === version);
    if (hit) return hit;
  }
  // preferred-version fallback
  const preferred = PREFERRED_VERSION_FOR[name];
  if (preferred) {
    const hit = equipment.find((e) => e.name === name && e.version === preferred);
    if (hit) return hit;
  }
  // empty-version canonical
  const canonical = equipment.find((e) => e.name === name && e.version === '');
  if (canonical) return canonical;
  // any version
  return equipment.find((e) => e.name === name) ?? null;
}

// =====
// Input shape from .scratch/vendor_starter.json
// =====
interface RawShopItem {
  name: string;
  wikiVersion: string;
  basePrice: number;
  stockBase: number;
}
interface RawShop {
  shop: string;
  shopLocation: string;
  items: RawShopItem[];
}

// =====
// Output shape
// =====
interface VendorItem {
  itemId: number;
  name: string;
  version: string;
  slot: EquipmentPiece['slot'];
  shops: { shop: string; location: string; basePrice: number; stockBase: number }[];
}

function emit(items: VendorItem[]): string {
  const slotOrder = ['head','cape','neck','ammo','weapon','body','shield','legs','hands','feet','ring'];
  items.sort((a, b) => {
    const da = slotOrder.indexOf(a.slot) - slotOrder.indexOf(b.slot);
    if (da !== 0) return da;
    return a.name.localeCompare(b.name);
  });

  const header = `// AUTO-GENERATED by src/tests/VendorStarterGen.test.ts — do not edit by hand.
// Source data:
//   - .scratch/vendor_starter.json (wiki-researched shop inventories, no-req only)
//   - Validated against cdn/json/equipment.json (item IDs canonical)
//   - Filtered through isCombatViable (src/lib/equipmentFilter.ts)
//
// Inclusion criteria:
//   - Shop: no quest/skill/minigame requirement to enter or trade
//   - Item: no wield/wear requirement (any req at all disqualifies)
//   - Item must have at least one positive combat stat (or be in noStatExceptions)
//
// Use this as the "worst-in-slot" starting baseline for ironman gear-progression.

export interface VendorItemShop {
  shop: string;
  location: string;
  basePrice: number;
  stockBase: number;
}

export interface VendorItem {
  itemId: number;
  name: string;
  version: string;
  slot: 'head' | 'cape' | 'neck' | 'ammo' | 'weapon' | 'body' | 'shield' | 'legs' | 'hands' | 'feet' | 'ring';
  shops: VendorItemShop[];
}
`;

  return `${header}\nexport const vendorStarterItems: VendorItem[] = ${JSON.stringify(items, null, 2)};\n`;
}

describe('VendorStarterGen', () => {
  test('compute + emit src/lib/vendorStarter.ts', () => {
    const raw = JSON.parse(
      fs.readFileSync(
        path.resolve(__dirname, '../../.scratch/vendor_starter.json'),
        'utf8',
      ),
    ) as RawShop[];

    // Resolve every (shop, item) row, then group by canonical item id.
    const byId = new Map<number, VendorItem>();
    const dropped: { name: string; version: string; reason: string }[] = [];

    for (const shop of raw) {
      for (const it of shop.items) {
        const piece = findEquip(it.name, it.wikiVersion);
        if (!piece) {
          dropped.push({ name: it.name, version: it.wikiVersion, reason: 'no equipment.json match' });
          continue;
        }
        if (!isCombatViable(piece)) {
          dropped.push({ name: piece.name, version: piece.version, reason: 'fails isCombatViable' });
          continue;
        }
        let entry = byId.get(piece.id);
        if (!entry) {
          entry = {
            itemId: piece.id,
            name: piece.name,
            version: piece.version,
            slot: piece.slot,
            shops: [],
          };
          byId.set(piece.id, entry);
        }
        entry.shops.push({
          shop: shop.shop,
          location: shop.shopLocation,
          basePrice: it.basePrice,
          stockBase: it.stockBase,
        });
      }
    }

    const items = [...byId.values()];
    const ts = emit(items);
    const outPath = path.resolve(__dirname, '../lib/vendorStarter.ts');
    fs.writeFileSync(outPath, ts, 'utf8');
    // eslint-disable-next-line no-console
    console.log(`\nWrote ${outPath} — ${items.length} unique items`);
    if (dropped.length) {
      // eslint-disable-next-line no-console
      console.log(`Dropped ${dropped.length} (${[...new Set(dropped.map((d) => d.name + (d.version ? ' (' + d.version + ')' : '')))].length} unique):`);
      const seen = new Set<string>();
      dropped.forEach((d) => {
        const k = d.name + '|' + d.version;
        if (seen.has(k)) return;
        seen.add(k);
        // eslint-disable-next-line no-console
        console.log(`  - ${d.name}${d.version ? ' (' + d.version + ')' : ''}: ${d.reason}`);
      });
    }
  });
});
