// AUTO-GENERATED by src/tests/BossDpsGen.test.ts — do not edit by hand.
// Source data:
//   - Wiki BIS: oldschool.runescape.wiki strategy pages (snapshot 2026-05)
//   - Temple IMEHB rates: /api/rates/ehb_rates.php?rate=im snapshot 2026-02-25
//   - DPS computed via the vendored weirdgloop calc engine (PlayerVsNPCCalc)
// To regenerate: `npx jest BossDpsGen`.
//
// Per-boss assumptions:
//   - All combat skills at 99
//   - Highest applicable offensive prayer + style potion buff
//   - Slayer helm (i) only equipped for slayer-locked bosses (on-task)
//   - Steady-state DPS only: no spec attacks, no gear swaps, no phase changes
//   - Raid + wave-based + multi-encounter entries omit DPS — see note

export type BossStyle = 'melee' | 'ranged' | 'magic';

export interface BossBis {
  style: BossStyle;
  stance: string;
  prayer: string;
  potion: string;
  onSlayerTask: boolean;
  monsterVersion: string;
  gear: {
    head: string | null;
    cape: string | null;
    neck: string | null;
    ammo: string | null;
    weapon: string | null;
    body: string | null;
    shield: string | null;
    legs: string | null;
    hands: string | null;
    feet: string | null;
    ring: string | null;
  };
}

export interface BossBaseline {
  name: string;
  kph: number;            // Temple IMEHB ironman rate
  bis?: BossBis;          // omitted for raid / multi-encounter / wave-based entries
  dps?: number;           // steady-state DPS against the named monster
  maxHit?: number;
  accuracy?: number;      // 0..1
  monsterHp?: number;
  ttkSec?: number;        // hp / dps (theoretical perfect TTK, no overkill)
  note?: string;
}

export const bossBaselines: BossBaseline[] = [
  {
    "name": "Abyssal Sire",
    "kph": 44,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Emberlight",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 8.5882,
    "maxHit": 59,
    "accuracy": 0.6983,
    "monsterHp": 425,
    "ttkSec": 49.49,
    "note": "Phase 2-4 melee; phase 1 respiratory swap ignored for steady-state calc"
  },
  {
    "name": "Alchemical Hydra",
    "kph": 29,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Dragon arrow",
        "weapon": "Twisted bow",
        "body": "Masori body (f)",
        "shield": null,
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Lightbearer"
      }
    },
    "dps": 11.8174,
    "maxHit": 79,
    "accuracy": 0.8972,
    "monsterHp": 1100,
    "ttkSec": 93.08,
    "note": "Tbow vs higher-magic phases; ZCB swap simplified out"
  },
  {
    "name": "Amoxliatl",
    "kph": 71,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Inquisitor's great helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Ghommal's lucky penny",
        "weapon": "Scythe of vitur",
        "body": "Inquisitor's hauberk",
        "shield": "Avernic defender",
        "legs": "Inquisitor's plateskirt",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 12.2682,
    "maxHit": 83,
    "accuracy": 0.8243,
    "monsterHp": 520,
    "ttkSec": 42.39,
    "note": "Scythe crush; multi-target with ice blocks"
  },
  {
    "name": "Araxxor",
    "kph": 38,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Inquisitor's hauberk",
        "shield": "Avernic defender",
        "legs": "Inquisitor's plateskirt",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 11.4339,
    "maxHit": 85,
    "accuracy": 0.8045,
    "monsterHp": 1020,
    "ttkSec": 89.21,
    "note": "Scythe crush; enrage phase mechanics simplified"
  },
  {
    "name": "Artio",
    "kph": 50,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Ava's assembler",
        "neck": "Necklace of anguish",
        "ammo": "Rada's blessing 4",
        "weapon": "Webweaver bow",
        "body": "Masori body (f)",
        "shield": "Twisted buckler",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Blessed boots",
        "ring": "Ring of shadows"
      }
    },
    "dps": 6.6276,
    "maxHit": 31,
    "accuracy": 0.7681,
    "monsterHp": 450,
    "ttkSec": 67.9,
    "note": "Wilderness setup, gear limited to reduce PK risk"
  },
  {
    "name": "Barrows Chests",
    "kph": 22,
    "note": "6 brothers, 4 styles required — no single-loadout DPS"
  },
  {
    "name": "Brutus",
    "kph": 250,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 12.8399,
    "maxHit": 78,
    "accuracy": 0.9839,
    "monsterHp": 58,
    "ttkSec": 4.52,
    "note": "New boss; wiki BIS sparse"
  },
  {
    "name": "Bryophyta",
    "kph": 9,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 11.7012,
    "maxHit": 78,
    "accuracy": 0.8967,
    "monsterHp": 115,
    "ttkSec": 9.83,
    "note": "Low-level boss; wiki lacks BIS list, applied generic top melee"
  },
  {
    "name": "Callisto",
    "kph": 142,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Ava's assembler",
        "neck": "Necklace of anguish",
        "ammo": "Rada's blessing 4",
        "weapon": "Webweaver bow",
        "body": "Masori body (f)",
        "shield": "Twisted buckler",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Blessed boots",
        "ring": "Ring of shadows"
      }
    },
    "dps": 5.4008,
    "maxHit": 31,
    "accuracy": 0.6259,
    "monsterHp": 1000,
    "ttkSec": 185.16,
    "note": "Wilderness; Webweaver bonus vs wildy monsters"
  },
  {
    "name": "Calvar'ion",
    "kph": 45,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Helm of neitiznot",
        "cape": "Infernal cape",
        "neck": "Salve amulet(ei)",
        "ammo": "Rada's blessing 4",
        "weapon": "Ursine chainmace",
        "body": "Fighter torso",
        "shield": "Avernic defender",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Dragon boots",
        "ring": "Ultor ring"
      }
    },
    "dps": 7.3527,
    "maxHit": 46,
    "accuracy": 0.7665,
    "monsterHp": 150,
    "ttkSec": 20.4,
    "note": "Wilderness; Salve(ei) stacks vs undead, crush style"
  },
  {
    "name": "Cerberus",
    "kph": 54,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Inquisitor's hauberk",
        "shield": "Avernic defender",
        "legs": "Inquisitor's plateskirt",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 11.8429,
    "maxHit": 85,
    "accuracy": 0.8333,
    "monsterHp": 600,
    "ttkSec": 50.66,
    "note": "Crush style; 5-tick scythe vs 6-tick boss yields 2-for-1 hits"
  },
  {
    "name": "Chambers of Xeric",
    "kph": 3.5,
    "note": "raid: multi-room, style switches per encounter"
  },
  {
    "name": "Chambers of Xeric Challenge Mode",
    "kph": 3,
    "note": "raid CM: multi-room, style switches per encounter"
  },
  {
    "name": "Chaos Elemental",
    "kph": 48,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Ursine chainmace",
        "body": "Black d'hide body",
        "shield": "Avernic defender",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Dragon boots",
        "ring": "Ultor ring"
      }
    },
    "dps": 2.8681,
    "maxHit": 40,
    "accuracy": 0.3438,
    "monsterHp": 250,
    "ttkSec": 87.16,
    "note": "Wilderness; gear minimized to limit PK loss"
  },
  {
    "name": "Chaos Fanatic",
    "kph": 80,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Ava's assembler",
        "neck": "Necklace of anguish",
        "ammo": "Rada's blessing 4",
        "weapon": "Webweaver bow",
        "body": "Masori body (f)",
        "shield": "Twisted buckler",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Mixed hide boots",
        "ring": "Ring of shadows"
      }
    },
    "dps": 5.4698,
    "maxHit": 31,
    "accuracy": 0.6339,
    "monsterHp": 225,
    "ttkSec": 41.14,
    "note": "Wilderness; Webweaver damage bonus"
  },
  {
    "name": "Commander Zilyana",
    "kph": 30,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Dragon arrow",
        "weapon": "Twisted bow",
        "body": "Masori body (f)",
        "shield": null,
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Ring of suffering (ri)"
      }
    },
    "dps": 5.9706,
    "maxHit": 70,
    "accuracy": 0.5116,
    "monsterHp": 255,
    "ttkSec": 42.71,
    "note": "Kiting strategy assumed"
  },
  {
    "name": "Corporeal Beast",
    "kph": 10,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Osmumten's fang",
        "body": "Masori body (f)",
        "shield": "Avernic defender",
        "legs": "Masori chaps (f)",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 5.8162,
    "maxHit": 41,
    "accuracy": 0.727,
    "monsterHp": 2000,
    "ttkSec": 343.87,
    "note": "Fang stab; Corp halves non-spear damage so Fang is BIS for stab"
  },
  {
    "name": "Crazy Archaeologist",
    "kph": 95,
    "bis": {
      "style": "magic",
      "stance": "Standard",
      "prayer": "AUGURY",
      "potion": "SATURATED_HEART",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Imbued saradomin cape",
        "neck": "Occult necklace",
        "ammo": "Rada's blessing 4",
        "weapon": "Accursed sceptre",
        "body": "Bloodbark body",
        "shield": "Elidinis' ward (f)",
        "legs": "Bloodbark legs",
        "hands": "Confliction gauntlets",
        "feet": "Mystic boots",
        "ring": "Ring of shadows"
      }
    },
    "dps": 6.5149,
    "maxHit": 33,
    "accuracy": 0.9459,
    "monsterHp": 225,
    "ttkSec": 34.54,
    "note": "Wilderness; magic, Accursed sceptre is wildy-bonus BIS here"
  },
  {
    "name": "Dagannoth Prime",
    "kph": 100,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Dragon arrow",
        "weapon": "Twisted bow",
        "body": "Masori body (f)",
        "shield": null,
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Venator ring"
      }
    },
    "dps": 9.9551,
    "maxHit": 73,
    "accuracy": 0.8179,
    "monsterHp": 255,
    "ttkSec": 25.61
  },
  {
    "name": "Dagannoth Rex",
    "kph": 100,
    "bis": {
      "style": "magic",
      "stance": "Standard",
      "prayer": "AUGURY",
      "potion": "SATURATED_HEART",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Ancestral hat",
        "cape": "Imbued saradomin cape",
        "neck": "Occult necklace",
        "ammo": "Rada's blessing 4",
        "weapon": "Eye of ayak",
        "body": "Ancestral robe top",
        "shield": "Elidinis' ward (f)",
        "legs": "Ancestral robe bottom",
        "hands": "Confliction gauntlets",
        "feet": "Avernic treads (max)",
        "ring": "Magus ring"
      }
    },
    "dps": 9.9203,
    "maxHit": 36,
    "accuracy": 0.9905,
    "monsterHp": 255,
    "ttkSec": 25.7,
    "note": "Magic vs Rex's very low magic defence"
  },
  {
    "name": "Dagannoth Supreme",
    "kph": 100,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 11.0903,
    "maxHit": 78,
    "accuracy": 0.8499,
    "monsterHp": 255,
    "ttkSec": 22.99
  },
  {
    "name": "Deranged Archaeologist",
    "kph": 95,
    "bis": {
      "style": "magic",
      "stance": "Standard",
      "prayer": "AUGURY",
      "potion": "SATURATED_HEART",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Ancestral hat",
        "cape": "Imbued saradomin cape",
        "neck": "Occult necklace",
        "ammo": "Rada's blessing 4",
        "weapon": "Tumeken's shadow",
        "body": "Ancestral robe top",
        "shield": null,
        "legs": "Ancestral robe bottom",
        "hands": "Confliction gauntlets",
        "feet": "Avernic treads (max)",
        "ring": "Magus ring"
      }
    },
    "dps": 10.1025,
    "maxHit": 62,
    "accuracy": 0.9772,
    "monsterHp": 200,
    "ttkSec": 19.8,
    "note": "Shadow is 2H; wiki notes very low magic defence"
  },
  {
    "name": "Doom of Mokhaiotl",
    "kph": 18,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Dragon arrow",
        "weapon": "Twisted bow",
        "body": "Masori body (f)",
        "shield": null,
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Lightbearer"
      }
    },
    "dps": 11.6714,
    "maxHit": 70,
    "accuracy": 1,
    "monsterHp": 625,
    "ttkSec": 53.55,
    "note": "New 2025 boss; Tbow exploits magic 275; ZCB spec swap simplified"
  },
  {
    "name": "Duke Sucellus",
    "kph": 37,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "Awake",
      "gear": {
        "head": "Oathplate helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Oathplate chest",
        "shield": "Avernic defender",
        "legs": "Oathplate legs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Bellator ring"
      }
    },
    "dps": 7.6151,
    "maxHit": 73,
    "accuracy": 0.6232,
    "monsterHp": 485,
    "ttkSec": 63.69,
    "note": "Slash; oathplate stacks slash accuracy"
  },
  {
    "name": "General Graardor",
    "kph": 31,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Osmumten's fang",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 4.4573,
    "maxHit": 44,
    "accuracy": 0.5244,
    "monsterHp": 255,
    "ttkSec": 57.21,
    "note": "Stab style; main fight only"
  },
  {
    "name": "Giant Mole",
    "kph": 97,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Dragon arrow",
        "weapon": "Twisted bow",
        "body": "Masori body (f)",
        "shield": null,
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Venator ring"
      }
    },
    "dps": 7.8545,
    "maxHit": 64,
    "accuracy": 0.736,
    "monsterHp": 200,
    "ttkSec": 25.46,
    "note": "Tbow ranged; off-task"
  },
  {
    "name": "Grotesque Guardians",
    "kph": 34,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 12.6662,
    "maxHit": 87,
    "accuracy": 0.8708,
    "monsterHp": 450,
    "ttkSec": 35.53,
    "note": "Rock hammer required for finisher; calc ignores that"
  },
  {
    "name": "Hespori",
    "kph": 50,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 10.9554,
    "maxHit": 78,
    "accuracy": 0.8395,
    "monsterHp": 300,
    "ttkSec": 27.38,
    "note": "Slash; flower phases use ranged swap (excluded)"
  },
  {
    "name": "Hueycoatl",
    "kph": 9,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Inquisitor's great helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Ghommal's lucky penny",
        "weapon": "Dragon hunter lance",
        "body": "Inquisitor's hauberk",
        "shield": "Avernic defender",
        "legs": "Inquisitor's plateskirt",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 6.8833,
    "maxHit": 49,
    "accuracy": 0.6737,
    "monsterHp": 2500,
    "ttkSec": 363.2,
    "note": "Head phase; DHL crush with dragonbane"
  },
  {
    "name": "K'ril Tsutsaroth",
    "kph": 32,
    "bis": {
      "style": "melee",
      "stance": "Controlled",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Unholy blessing",
        "weapon": "Emberlight",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Bellator ring"
      }
    },
    "dps": 6.1854,
    "maxHit": 51,
    "accuracy": 0.5817,
    "monsterHp": 255,
    "ttkSec": 41.23,
    "note": "Demonbane Emberlight; main fight"
  },
  {
    "name": "Kalphite Queen",
    "kph": 37,
    "bis": {
      "style": "melee",
      "stance": "Controlled",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Keris partisan of breaching",
        "body": "Inquisitor's hauberk",
        "shield": "Avernic defender",
        "legs": "Inquisitor's plateskirt",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 3.5225,
    "maxHit": 147,
    "accuracy": 0.3318,
    "monsterHp": 255,
    "ttkSec": 72.39,
    "note": "Phase 1 melee; phase 2 (flying) needs ranged swap, excluded"
  },
  {
    "name": "King Black Dragon",
    "kph": 75,
    "bis": {
      "style": "melee",
      "stance": "Controlled",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Dragon hunter lance",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 6.6878,
    "maxHit": 51,
    "accuracy": 0.629,
    "monsterHp": 240,
    "ttkSec": 35.89,
    "note": "DHL stab vs dragon"
  },
  {
    "name": "Kraken",
    "kph": 90,
    "bis": {
      "style": "magic",
      "stance": "Standard",
      "prayer": "AUGURY",
      "potion": "SATURATED_HEART",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Imbued saradomin cape",
        "neck": "Occult necklace",
        "ammo": "Rada's blessing 4",
        "weapon": "Tumeken's shadow",
        "body": "Ancestral robe top",
        "shield": null,
        "legs": "Ancestral robe bottom",
        "hands": "Confliction gauntlets",
        "feet": "Avernic treads (max)",
        "ring": "Magus ring"
      }
    },
    "dps": 11.0502,
    "maxHit": 67,
    "accuracy": 0.9891,
    "monsterHp": 255,
    "ttkSec": 23.08,
    "note": "Shadow 2H; trident is cheaper alternative"
  },
  {
    "name": "Kree'arra",
    "kph": 30,
    "bis": {
      "style": "magic",
      "stance": "Standard",
      "prayer": "AUGURY",
      "potion": "SATURATED_HEART",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Ancestral hat",
        "cape": "Imbued zamorak cape",
        "neck": "Occult necklace",
        "ammo": "Rada's blessing 4",
        "weapon": "Tumeken's shadow",
        "body": "Ancestral robe top",
        "shield": null,
        "legs": "Ancestral robe bottom",
        "hands": "Confliction gauntlets",
        "feet": "Avernic treads (max)",
        "ring": "Magus ring"
      }
    },
    "dps": 6.7612,
    "maxHit": 62,
    "accuracy": 0.654,
    "monsterHp": 255,
    "ttkSec": 37.72,
    "note": "Shadow 2H; PfM mandatory throughout"
  },
  {
    "name": "Lunar Chests",
    "kph": 18,
    "note": "rotating 3-boss minigame, mixed styles"
  },
  {
    "name": "Mimic",
    "kph": 50,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 7.3413,
    "maxHit": 78,
    "accuracy": 0.5626,
    "monsterHp": 230,
    "ttkSec": 31.33,
    "note": "Wiki sparse; quest minigame, generic top melee applied"
  },
  {
    "name": "Nex",
    "kph": 15,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of blood fury",
        "ammo": "Rada's blessing 4",
        "weapon": "Osmumten's fang",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Lightbearer"
      }
    },
    "dps": 5.4824,
    "maxHit": 40,
    "accuracy": 0.6999,
    "monsterHp": 3400,
    "ttkSec": 620.17,
    "note": "Fang+Torva hybrid; Nex always uses swaps, this is simplified"
  },
  {
    "name": "Obor",
    "kph": 12,
    "bis": {
      "style": "ranged",
      "stance": "Accurate",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": null,
        "weapon": "Toxic blowpipe",
        "body": "Masori body (f)",
        "shield": null,
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Venator ring"
      }
    },
    "dps": 7.3541,
    "maxHit": 29,
    "accuracy": 0.9108,
    "monsterHp": 120,
    "ttkSec": 16.32,
    "note": "Low-level boss; wiki recommends blowpipe for fast kills"
  },
  {
    "name": "Phantom Muspah",
    "kph": 27,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Ruby dragon bolts (e)",
        "weapon": "Zaryte crossbow",
        "body": "Masori body (f)",
        "shield": "Twisted buckler",
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Lightbearer"
      }
    },
    "dps": 2.9517,
    "maxHit": 44,
    "accuracy": 0.3246,
    "monsterHp": 850,
    "ttkSec": 287.97,
    "note": "Shielded ranged phase; ruby bolts proc for DPS"
  },
  {
    "name": "Phosani's Nightmare",
    "kph": 9.3,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Inquisitor's great helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Inquisitor's hauberk",
        "shield": "Avernic defender",
        "legs": "Inquisitor's plateskirt",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 8.8397,
    "maxHit": 77,
    "accuracy": 0.6862,
    "monsterHp": 3200,
    "ttkSec": 362,
    "note": "Crush; desperation phase voidwaker swap excluded"
  },
  {
    "name": "Sarachnis",
    "kph": 67,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Oathplate helm",
        "cape": "Infernal cape",
        "neck": "Amulet of blood fury",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Masori body (f)",
        "shield": "Avernic defender",
        "legs": "Masori chaps (f)",
        "hands": "Ferocious gloves",
        "feet": "Aranea boots",
        "ring": "Ultor ring"
      }
    },
    "dps": 8.2355,
    "maxHit": 71,
    "accuracy": 0.6928,
    "monsterHp": 400,
    "ttkSec": 48.57,
    "note": "Crush; aranea boots negate web attack"
  },
  {
    "name": "Scorpia",
    "kph": 80,
    "bis": {
      "style": "magic",
      "stance": "Standard",
      "prayer": "AUGURY",
      "potion": "SATURATED_HEART",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Imbued saradomin cape",
        "neck": "Occult necklace",
        "ammo": "Rada's blessing 4",
        "weapon": "Accursed sceptre",
        "body": "Bloodbark body",
        "shield": "Elidinis' ward (f)",
        "legs": "Bloodbark legs",
        "hands": "Confliction gauntlets",
        "feet": "Bloodbark boots",
        "ring": "Ring of shadows"
      }
    },
    "dps": 6.7554,
    "maxHit": 33,
    "accuracy": 0.9809,
    "monsterHp": 200,
    "ttkSec": 29.61,
    "note": "Wilderness; magic with ice barrage typical"
  },
  {
    "name": "Scurrius",
    "kph": 60,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 11.28,
    "maxHit": 78,
    "accuracy": 0.8644,
    "monsterHp": 1500,
    "ttkSec": 132.98,
    "note": "Solo; scythe excels in rat-spawn phases"
  },
  {
    "name": "Shellbane Gryphon",
    "kph": 95,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Tortugan shield",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 11.4589,
    "maxHit": 81,
    "accuracy": 0.8458,
    "monsterHp": 400,
    "ttkSec": 34.91,
    "note": "Tortugan shield required; new boss, sparse data"
  },
  {
    "name": "Skotizo",
    "kph": 38,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Emberlight",
        "body": "Oathplate chest",
        "shield": "Avernic defender",
        "legs": "Oathplate legs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 8.7569,
    "maxHit": 56,
    "accuracy": 0.7501,
    "monsterHp": 450,
    "ttkSec": 51.39,
    "note": "Demonbane; altar-disabling Emberlight"
  },
  {
    "name": "Sol Heredit",
    "kph": 2.8,
    "note": "wave-based (Colosseum): full 12-wave completion"
  },
  {
    "name": "Spindel",
    "kph": 50,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Ursine chainmace",
        "body": "Fighter torso",
        "shield": "Avernic defender",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Dragon boots",
        "ring": "Ultor ring"
      }
    },
    "dps": 5.6709,
    "maxHit": 41,
    "accuracy": 0.6631,
    "monsterHp": 515,
    "ttkSec": 90.81,
    "note": "Wildy spider variant; crush"
  },
  {
    "name": "The Corrupted Gauntlet",
    "kph": 7.2,
    "note": "minigame: corrupted variant, custom crystal gear inside"
  },
  {
    "name": "The Gauntlet",
    "kph": 10,
    "note": "minigame: crystal-prep gauntlet, custom gear inside"
  },
  {
    "name": "The Leviathan",
    "kph": 27,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "Awake",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Ruby dragon bolts (e)",
        "weapon": "Zaryte crossbow",
        "body": "Masori body (f)",
        "shield": "Twisted buckler",
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Lightbearer"
      }
    },
    "dps": 5.7903,
    "maxHit": 44,
    "accuracy": 0.7386,
    "monsterHp": 900,
    "ttkSec": 155.43,
    "note": "ZCB until 450hp then blowpipe swap (excluded from calc)"
  },
  {
    "name": "The Nightmare",
    "kph": 11,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Inquisitor's great helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Inquisitor's hauberk",
        "shield": "Avernic defender",
        "legs": "Inquisitor's plateskirt",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 8.8397,
    "maxHit": 77,
    "accuracy": 0.6862,
    "monsterHp": 2400,
    "ttkSec": 271.5,
    "note": "Crush; main DPS phase"
  },
  {
    "name": "The Royal Titans",
    "kph": 55,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 7.3007,
    "maxHit": 45,
    "accuracy": 0.9725,
    "monsterHp": 40,
    "ttkSec": 5.48,
    "note": "2-target boss favors scythe; wiki BIS table sparse"
  },
  {
    "name": "The Whisperer",
    "kph": 21,
    "bis": {
      "style": "magic",
      "stance": "Standard",
      "prayer": "AUGURY",
      "potion": "SATURATED_HEART",
      "onSlayerTask": false,
      "monsterVersion": "Awake",
      "gear": {
        "head": "Ancestral hat",
        "cape": "Imbued saradomin cape",
        "neck": "Occult necklace",
        "ammo": "Rada's blessing 4",
        "weapon": "Tumeken's shadow",
        "body": "Ancestral robe top",
        "shield": null,
        "legs": "Ancestral robe bottom",
        "hands": "Confliction gauntlets",
        "feet": "Avernic treads (max)",
        "ring": "Magus ring"
      }
    },
    "dps": 9.4317,
    "maxHit": 62,
    "accuracy": 0.9123,
    "monsterHp": 900,
    "ttkSec": 95.42,
    "note": "Souls phase needs venator bow swap; using main magic setup"
  },
  {
    "name": "Theatre of Blood",
    "kph": 3.2,
    "note": "raid: 6 rooms, melee/ranged/magic across encounters"
  },
  {
    "name": "Theatre of Blood Challenge Mode",
    "kph": 3,
    "note": "raid HM: 6 rooms, melee/ranged/magic across encounters"
  },
  {
    "name": "Thermonuclear Smoke Devil",
    "kph": 100,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": true,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Scythe of vitur",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Bellator ring"
      }
    },
    "dps": 10.0003,
    "maxHit": 85,
    "accuracy": 0.7036,
    "monsterHp": 240,
    "ttkSec": 24,
    "note": "Slash; on-task slayer helm"
  },
  {
    "name": "Tombs of Amascut",
    "kph": 3.7,
    "note": "raid: scalable invocations, all 3 styles used"
  },
  {
    "name": "Tombs of Amascut Expert",
    "kph": 3,
    "note": "raid expert: scalable invocations, all 3 styles used"
  },
  {
    "name": "TzKal-Zuk",
    "kph": 1,
    "note": "wave-based (Inferno): full completion incl 60+ waves"
  },
  {
    "name": "TzTok-Jad",
    "kph": 2.2,
    "note": "wave-based (Fight Caves): full completion incl 63 waves"
  },
  {
    "name": "Vardorvis",
    "kph": 37,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "Awake",
      "gear": {
        "head": "Oathplate helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Soulreaper axe",
        "body": "Oathplate chest",
        "shield": "Avernic defender",
        "legs": "Oathplate legs",
        "hands": "Ferocious gloves",
        "feet": "Echo boots",
        "ring": "Bellator ring"
      }
    },
    "dps": 6.2762,
    "maxHit": 51,
    "accuracy": 0.7378,
    "monsterHp": 700,
    "ttkSec": 111.53,
    "note": "Slash; scythe ineffective due to 2x2 size"
  },
  {
    "name": "Venenatis",
    "kph": 80,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Slayer helmet (i)",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Ursine chainmace",
        "body": "Fighter torso",
        "shield": "Avernic defender",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Dragon boots",
        "ring": "Ultor ring"
      }
    },
    "dps": 4.4892,
    "maxHit": 41,
    "accuracy": 0.525,
    "monsterHp": 850,
    "ttkSec": 189.34,
    "note": "Wilderness; crush; gear limited for PK risk"
  },
  {
    "name": "Vet'ion",
    "kph": 39,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Helm of neitiznot",
        "cape": "Infernal cape",
        "neck": "Salve amulet(ei)",
        "ammo": "Rada's blessing 4",
        "weapon": "Ursine chainmace",
        "body": "Black d'hide body",
        "shield": "Avernic defender",
        "legs": "Black d'hide chaps",
        "hands": "Barrows gloves",
        "feet": "Dragon boots",
        "ring": "Ultor ring"
      }
    },
    "dps": 5.6017,
    "maxHit": 45,
    "accuracy": 0.5969,
    "monsterHp": 255,
    "ttkSec": 45.52,
    "note": "Wilderness; salve(ei) stacks vs undead; crush"
  },
  {
    "name": "Vorkath",
    "kph": 34,
    "bis": {
      "style": "melee",
      "stance": "Controlled",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "Post-quest",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Salve amulet(ei)",
        "ammo": "Rada's blessing 4",
        "weapon": "Dragon hunter lance",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 8.8379,
    "maxHit": 58,
    "accuracy": 0.731,
    "monsterHp": 750,
    "ttkSec": 84.86,
    "note": "DHL stab+salve stacking; PfM throughout"
  },
  {
    "name": "Yama",
    "kph": 18,
    "bis": {
      "style": "melee",
      "stance": "Aggressive",
      "prayer": "PIETY",
      "potion": "SUPER_COMBAT",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Torva full helm",
        "cape": "Infernal cape",
        "neck": "Amulet of rancour",
        "ammo": "Rada's blessing 4",
        "weapon": "Emberlight",
        "body": "Torva platebody",
        "shield": "Avernic defender",
        "legs": "Torva platelegs",
        "hands": "Ferocious gloves",
        "feet": "Avernic treads (max)",
        "ring": "Ultor ring"
      }
    },
    "dps": 7.9652,
    "maxHit": 58,
    "accuracy": 0.6588,
    "monsterHp": 2500,
    "ttkSec": 313.87,
    "note": "Demonbane; slash; elder maul defence reduction excluded"
  },
  {
    "name": "Zulrah",
    "kph": 42,
    "bis": {
      "style": "ranged",
      "stance": "Rapid",
      "prayer": "RIGOUR",
      "potion": "RANGING",
      "onSlayerTask": false,
      "monsterVersion": "",
      "gear": {
        "head": "Masori mask (f)",
        "cape": "Dizana's quiver",
        "neck": "Necklace of anguish",
        "ammo": "Dragon arrow",
        "weapon": "Twisted bow",
        "body": "Masori body (f)",
        "shield": null,
        "legs": "Masori chaps (f)",
        "hands": "Zaryte vambraces",
        "feet": "Avernic treads (max)",
        "ring": "Ring of suffering (ri)"
      }
    },
    "dps": 2.41,
    "maxHit": 50,
    "accuracy": 0.2306,
    "monsterHp": 500,
    "ttkSec": 207.47,
    "note": "Tbow simplifies rotation across all 3 phases (wiki-noted approach)"
  }
];
