// AUTO-GENERATED by src/tests/BossDropsGen.test.ts -- do not edit by hand.
// Source: bossAccess fields from .scratch/boss_drops.json, extracted into
// a flat registry parallel to src/lib/questRequirements.ts.
//
// Skill keys use long-form OSRS names (attack/strength/defence/hitpoints/
// ranged/magic/prayer/slayer/...) so they match the /api/lookup-player
// response and questRequirements.ts.
//
// slayerLevel from bossAccess is folded into skills.slayer. onSlayerTask
// is kept as a separate informational field — it doesn't block
// killableBosses() since the player can always go get a task; it just
// tells the UI that the boss is task-gated.

export type AllSkills = Record<string, number>;

export interface BossReq {
  /** Skill thresholds (long-form OSRS names, incl. 'slayer'). */
  skills?: AllSkills;
  /** Quests that must be COMPLETED to attempt this boss. */
  questsCompleted?: string[];
  /** Quests that must be at least STARTED. */
  questsStarted?: string[];
  /**
   * True when the boss is locked to a specific slayer task. Does NOT
   * block killableBosses() since the player can always go get a task,
   * but kept here so the UI can label task-gated bosses.
   */
  onSlayerTask?: boolean;
}

export const BOSS_REQS: Record<string, BossReq> = {
  "Abyssal Sire": {
    "skills": {
      "slayer": 85
    },
    "onSlayerTask": true
  },
  "Alchemical Hydra": {
    "skills": {
      "slayer": 95
    },
    "onSlayerTask": true
  },
  "Amoxliatl": {
    "skills": {
      "slayer": 48
    },
    "questsCompleted": [
      "The Heart of Darkness"
    ]
  },
  "Araxxor": {
    "skills": {
      "slayer": 92
    },
    "onSlayerTask": true
  },
  "Artio": {},
  "Barrows Chests": {
    "questsCompleted": [
      "Priest in Peril"
    ]
  },
  "Brutus": {
    "questsCompleted": [
      "The Ides of Milk"
    ]
  },
  "Bryophyta": {},
  "Callisto": {},
  "Calvar'ion": {},
  "Cerberus": {
    "skills": {
      "slayer": 91
    },
    "onSlayerTask": true
  },
  "Chambers of Xeric": {},
  "Chambers of Xeric Challenge Mode": {},
  "Chaos Elemental": {},
  "Chaos Fanatic": {},
  "Commander Zilyana": {
    "skills": {
      "agility": 70
    }
  },
  "Corporeal Beast": {},
  "Crazy Archaeologist": {},
  "Dagannoth Prime": {},
  "Dagannoth Rex": {},
  "Dagannoth Supreme": {},
  "Deranged Archaeologist": {
    "questsCompleted": [
      "Bone Voyage"
    ]
  },
  "Doom of Mokhaiotl": {
    "questsCompleted": [
      "The Final Dawn"
    ]
  },
  "Duke Sucellus": {
    "questsCompleted": [
      "Desert Treasure II - The Fallen Empire"
    ]
  },
  "General Graardor": {
    "skills": {
      "strength": 70
    }
  },
  "Giant Mole": {},
  "Grotesque Guardians": {
    "skills": {
      "slayer": 75
    },
    "onSlayerTask": true
  },
  "Hespori": {
    "skills": {
      "farming": 65
    }
  },
  "Hueycoatl": {},
  "K'ril Tsutsaroth": {
    "skills": {
      "hitpoints": 70
    }
  },
  "Kalphite Queen": {},
  "King Black Dragon": {},
  "Kraken": {
    "skills": {
      "magic": 50,
      "slayer": 87
    },
    "onSlayerTask": true
  },
  "Kree'arra": {
    "skills": {
      "ranged": 70
    }
  },
  "Lunar Chests": {
    "questsCompleted": [
      "Perilous Moons"
    ]
  },
  "Mimic": {},
  "Nex": {
    "skills": {
      "hitpoints": 70,
      "ranged": 70,
      "strength": 70,
      "agility": 70
    },
    "questsCompleted": [
      "Desert Treasure I",
      "The Frozen Door"
    ]
  },
  "Obor": {},
  "Phantom Muspah": {
    "questsCompleted": [
      "Secrets of the North"
    ]
  },
  "Phosani's Nightmare": {},
  "Sarachnis": {},
  "Scorpia": {},
  "Scurrius": {},
  "Shellbane Gryphon": {
    "skills": {
      "slayer": 51
    },
    "questsCompleted": [
      "Troubled Tortugans"
    ],
    "onSlayerTask": true
  },
  "Skotizo": {},
  "Sol Heredit": {
    "questsCompleted": [
      "Children of the Sun"
    ]
  },
  "Spindel": {},
  "The Corrupted Gauntlet": {
    "questsCompleted": [
      "Song of the Elves"
    ]
  },
  "The Gauntlet": {
    "questsCompleted": [
      "Song of the Elves"
    ]
  },
  "The Leviathan": {
    "questsCompleted": [
      "Desert Treasure II - The Fallen Empire"
    ]
  },
  "The Nightmare": {},
  "The Royal Titans": {},
  "The Whisperer": {
    "questsCompleted": [
      "Desert Treasure II - The Fallen Empire"
    ]
  },
  "Theatre of Blood": {
    "questsCompleted": [
      "Priest in Peril"
    ]
  },
  "Theatre of Blood Challenge Mode": {
    "questsCompleted": [
      "Priest in Peril"
    ]
  },
  "Thermonuclear Smoke Devil": {
    "skills": {
      "slayer": 93
    },
    "onSlayerTask": true
  },
  "Tombs of Amascut": {
    "questsCompleted": [
      "Beneath Cursed Sands"
    ]
  },
  "Tombs of Amascut Expert": {
    "questsCompleted": [
      "Beneath Cursed Sands"
    ]
  },
  "TzKal-Zuk": {},
  "TzTok-Jad": {},
  "Vardorvis": {
    "questsCompleted": [
      "Desert Treasure II - The Fallen Empire"
    ]
  },
  "Venenatis": {},
  "Vet'ion": {},
  "Vorkath": {
    "questsCompleted": [
      "Dragon Slayer II"
    ]
  },
  "Yama": {
    "questsCompleted": [
      "A Kingdom Divided"
    ]
  },
  "Zulrah": {
    "questsStarted": [
      "Regicide"
    ]
  }
};

/**
 * Returns the subset of `bossList` the player can kill given their
 * current skills + quest state. Mirrors autocompletableQuests() from
 * questRequirements.ts.
 *
 * Excludes bosses where any of the following fails:
 *   - Any required skill threshold (incl. slayer) not met.
 *   - Any required completed quest not in questsCompleted.
 *   - Any required started quest not in questsStarted ∪ questsCompleted.
 *
 * Does NOT exclude based on onSlayerTask — the player can always go get
 * the task. If a boss is missing from the registry, treat it as killable
 * (no listed reqs).
 */
export function killableBosses(
  bossList: readonly string[],
  skills: AllSkills,
  questsCompleted: ReadonlySet<string>,
  questsStarted: ReadonlySet<string>,
): string[] {
  const out: string[] = [];
  for (const boss of bossList) {
    const req = BOSS_REQS[boss];
    if (!req) { out.push(boss); continue; }

    let ok = true;
    for (const [skill, lvl] of Object.entries(req.skills ?? {})) {
      if ((skills[skill] ?? 1) < lvl) { ok = false; break; }
    }
    if (!ok) continue;

    for (const q of req.questsCompleted ?? []) {
      if (!questsCompleted.has(q)) { ok = false; break; }
    }
    if (!ok) continue;

    for (const q of req.questsStarted ?? []) {
      if (!questsStarted.has(q) && !questsCompleted.has(q)) { ok = false; break; }
    }
    if (!ok) continue;

    out.push(boss);
  }
  return out;
}

/**
 * Collect every quest name referenced by any boss's access reqs — for
 * the /crabsim "auto-complete all relevant quests" preset, analogous to
 * allVendorQuestNames().
 */
export function allBossQuestNames(): { started: string[]; completed: string[] } {
  const started = new Set<string>();
  const completed = new Set<string>();
  for (const req of Object.values(BOSS_REQS)) {
    for (const q of req.questsCompleted ?? []) completed.add(q);
    for (const q of req.questsStarted ?? []) started.add(q);
  }
  // Completed implies started.
  for (const q of completed) started.add(q);
  return { started: [...started], completed: [...completed] };
}
