// AUTO-GENERATED by src/tests/VendorStarterGen.test.ts — do not edit by hand.
// Source data:
//   - .scratch/vendor_starter.json (wiki-researched shop inventories, no-req only)
//   - Validated against cdn/json/equipment.json (item IDs canonical)
//   - Filtered through isCombatViable (src/lib/equipmentFilter.ts)
//
// Inclusion criteria:
//   - Shop: no quest/skill/minigame requirement to enter or trade
//   - Item: no wield/wear requirement (any req at all disqualifies)
//   - Item must have at least one positive combat stat (or be in noStatExceptions)
//
// Use this as the "worst-in-slot" starting baseline for ironman gear-progression.

export interface VendorItemShop {
  shop: string;
  location: string;
  basePrice: number;
  stockBase: number;
}

export interface VendorItem {
  itemId: number;
  name: string;
  version: string;
  slot: 'head' | 'cape' | 'neck' | 'ammo' | 'weapon' | 'body' | 'shield' | 'legs' | 'hands' | 'feet' | 'ring';
  shops: VendorItemShop[];
}

export const vendorStarterItems: VendorItem[] = [
  {
    "itemId": 579,
    "name": "Blue wizard hat",
    "version": "",
    "slot": "head",
    "shops": [
      {
        "shop": "Fancy Clothes Store",
        "location": "Varrock",
        "basePrice": 2,
        "stockBase": 3
      },
      {
        "shop": "Betty's Magic Emporium",
        "location": "Port Sarim",
        "basePrice": 2,
        "stockBase": 1
      }
    ]
  },
  {
    "itemId": 1155,
    "name": "Bronze full helm",
    "version": "",
    "slot": "head",
    "shops": [
      {
        "shop": "Peksa's Helmet Shop",
        "location": "Barbarian Village",
        "basePrice": 44,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 1139,
    "name": "Bronze med helm",
    "version": "",
    "slot": "head",
    "shops": [
      {
        "shop": "Peksa's Helmet Shop",
        "location": "Barbarian Village",
        "basePrice": 24,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1153,
    "name": "Iron full helm",
    "version": "",
    "slot": "head",
    "shops": [
      {
        "shop": "Peksa's Helmet Shop",
        "location": "Barbarian Village",
        "basePrice": 154,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1137,
    "name": "Iron med helm",
    "version": "",
    "slot": "head",
    "shops": [
      {
        "shop": "Peksa's Helmet Shop",
        "location": "Barbarian Village",
        "basePrice": 84,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1017,
    "name": "Wizard hat",
    "version": "",
    "slot": "head",
    "shops": [
      {
        "shop": "Betty's Magic Emporium",
        "location": "Port Sarim",
        "basePrice": 2,
        "stockBase": 1
      }
    ]
  },
  {
    "itemId": 1007,
    "name": "Red cape",
    "version": "",
    "slot": "cape",
    "shops": [
      {
        "shop": "Thessalia's Fine Clothes",
        "location": "Varrock",
        "basePrice": 2,
        "stockBase": 4
      },
      {
        "shop": "Fancy Clothes Store",
        "location": "Varrock",
        "basePrice": 2,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 1023,
    "name": "Yellow cape",
    "version": "",
    "slot": "cape",
    "shops": [
      {
        "shop": "Fancy Clothes Store",
        "location": "Varrock",
        "basePrice": 41,
        "stockBase": 1
      }
    ]
  },
  {
    "itemId": 882,
    "name": "Bronze arrow",
    "version": "Unpoisoned",
    "slot": "ammo",
    "shops": [
      {
        "shop": "Lowe's Archery Emporium",
        "location": "Varrock",
        "basePrice": 1,
        "stockBase": 2000
      },
      {
        "shop": "Hickton's Archery Emporium",
        "location": "Catherby",
        "basePrice": 1,
        "stockBase": 1000
      }
    ]
  },
  {
    "itemId": 877,
    "name": "Bronze bolts",
    "version": "Unpoisoned",
    "slot": "ammo",
    "shops": [
      {
        "shop": "Lowe's Archery Emporium",
        "location": "Varrock",
        "basePrice": 1,
        "stockBase": 1500
      },
      {
        "shop": "Hickton's Archery Emporium",
        "location": "Catherby",
        "basePrice": 1,
        "stockBase": 200
      }
    ]
  },
  {
    "itemId": 1307,
    "name": "Bronze 2h sword",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Gaius' Two Handed Shop",
        "location": "Taverley",
        "basePrice": 80,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 1351,
    "name": "Bronze axe",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Bob's Brilliant Axes",
        "location": "Lumbridge",
        "basePrice": 16,
        "stockBase": 10
      }
    ]
  },
  {
    "itemId": 1375,
    "name": "Bronze battleaxe",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Brian's Battleaxe Bazaar",
        "location": "Port Sarim",
        "basePrice": 52,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 1205,
    "name": "Bronze dagger",
    "version": "Unpoisoned",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Varrock Swordshop",
        "location": "Varrock",
        "basePrice": 10,
        "stockBase": 10
      }
    ]
  },
  {
    "itemId": 1291,
    "name": "Bronze longsword",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Varrock Swordshop",
        "location": "Varrock",
        "basePrice": 40,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 1422,
    "name": "Bronze mace",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Flynn's Mace Market",
        "location": "Falador",
        "basePrice": 18,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1265,
    "name": "Bronze pickaxe",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Bob's Brilliant Axes",
        "location": "Lumbridge",
        "basePrice": 1,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1321,
    "name": "Bronze scimitar",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zeke's Superior Scimitars",
        "location": "Al Kharid",
        "basePrice": 32,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1277,
    "name": "Bronze sword",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Varrock Swordshop",
        "location": "Varrock",
        "basePrice": 26,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 837,
    "name": "Crossbow",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Lowe's Archery Emporium",
        "location": "Varrock",
        "basePrice": 70,
        "stockBase": 2
      },
      {
        "shop": "Hickton's Archery Emporium",
        "location": "Catherby",
        "basePrice": 70,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1309,
    "name": "Iron 2h sword",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Gaius' Two Handed Shop",
        "location": "Taverley",
        "basePrice": 280,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1349,
    "name": "Iron axe",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Bob's Brilliant Axes",
        "location": "Lumbridge",
        "basePrice": 56,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1363,
    "name": "Iron battleaxe",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Bob's Brilliant Axes",
        "location": "Lumbridge",
        "basePrice": 182,
        "stockBase": 5
      },
      {
        "shop": "Brian's Battleaxe Bazaar",
        "location": "Port Sarim",
        "basePrice": 182,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1203,
    "name": "Iron dagger",
    "version": "Unpoisoned",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Varrock Swordshop",
        "location": "Varrock",
        "basePrice": 35,
        "stockBase": 6
      }
    ]
  },
  {
    "itemId": 1293,
    "name": "Iron longsword",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Varrock Swordshop",
        "location": "Varrock",
        "basePrice": 140,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1420,
    "name": "Iron mace",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Flynn's Mace Market",
        "location": "Falador",
        "basePrice": 63,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 1323,
    "name": "Iron scimitar",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zeke's Superior Scimitars",
        "location": "Al Kharid",
        "basePrice": 112,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1279,
    "name": "Iron sword",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Varrock Swordshop",
        "location": "Varrock",
        "basePrice": 91,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 839,
    "name": "Longbow",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Lowe's Archery Emporium",
        "location": "Varrock",
        "basePrice": 80,
        "stockBase": 4
      },
      {
        "shop": "Hickton's Archery Emporium",
        "location": "Catherby",
        "basePrice": 80,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1389,
    "name": "Magic staff",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zaff's Superior Staffs",
        "location": "Varrock",
        "basePrice": 200,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 841,
    "name": "Shortbow",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Lowe's Archery Emporium",
        "location": "Varrock",
        "basePrice": 50,
        "stockBase": 4
      },
      {
        "shop": "Hickton's Archery Emporium",
        "location": "Catherby",
        "basePrice": 50,
        "stockBase": 4
      }
    ]
  },
  {
    "itemId": 1379,
    "name": "Staff",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zaff's Superior Staffs",
        "location": "Varrock",
        "basePrice": 15,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1381,
    "name": "Staff of air",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zaff's Superior Staffs",
        "location": "Varrock",
        "basePrice": 1500,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1385,
    "name": "Staff of earth",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zaff's Superior Staffs",
        "location": "Varrock",
        "basePrice": 1500,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1387,
    "name": "Staff of fire",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zaff's Superior Staffs",
        "location": "Varrock",
        "basePrice": 1500,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1383,
    "name": "Staff of water",
    "version": "",
    "slot": "weapon",
    "shops": [
      {
        "shop": "Zaff's Superior Staffs",
        "location": "Varrock",
        "basePrice": 1500,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1103,
    "name": "Bronze chainbody",
    "version": "",
    "slot": "body",
    "shops": [
      {
        "shop": "Horvik's Armour Shop",
        "location": "Varrock",
        "basePrice": 60,
        "stockBase": 5
      },
      {
        "shop": "Wayne's Chains - Chainmail specialist",
        "location": "Falador",
        "basePrice": 60,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1117,
    "name": "Bronze platebody",
    "version": "",
    "slot": "body",
    "shops": [
      {
        "shop": "Horvik's Armour Shop",
        "location": "Varrock",
        "basePrice": 160,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1101,
    "name": "Iron chainbody",
    "version": "",
    "slot": "body",
    "shops": [
      {
        "shop": "Horvik's Armour Shop",
        "location": "Varrock",
        "basePrice": 210,
        "stockBase": 3
      },
      {
        "shop": "Wayne's Chains - Chainmail specialist",
        "location": "Falador",
        "basePrice": 210,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1115,
    "name": "Iron platebody",
    "version": "",
    "slot": "body",
    "shops": [
      {
        "shop": "Horvik's Armour Shop",
        "location": "Varrock",
        "basePrice": 560,
        "stockBase": 1
      }
    ]
  },
  {
    "itemId": 1129,
    "name": "Leather body",
    "version": "",
    "slot": "body",
    "shops": [
      {
        "shop": "Thessalia's Fine Clothes",
        "location": "Varrock",
        "basePrice": 21,
        "stockBase": 12
      }
    ]
  },
  {
    "itemId": 426,
    "name": "Priest gown (top)",
    "version": "",
    "slot": "body",
    "shops": [
      {
        "shop": "Thessalia's Fine Clothes",
        "location": "Varrock",
        "basePrice": 5,
        "stockBase": 3
      },
      {
        "shop": "Fancy Clothes Store",
        "location": "Varrock",
        "basePrice": 6,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1189,
    "name": "Bronze kiteshield",
    "version": "",
    "slot": "shield",
    "shops": [
      {
        "shop": "Cassie's Shield Shop",
        "location": "Falador",
        "basePrice": 68,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1173,
    "name": "Bronze sq shield",
    "version": "",
    "slot": "shield",
    "shops": [
      {
        "shop": "Cassie's Shield Shop",
        "location": "Falador",
        "basePrice": 48,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1175,
    "name": "Iron sq shield",
    "version": "",
    "slot": "shield",
    "shops": [
      {
        "shop": "Cassie's Shield Shop",
        "location": "Falador",
        "basePrice": 168,
        "stockBase": 2
      }
    ]
  },
  {
    "itemId": 1171,
    "name": "Wooden shield",
    "version": "",
    "slot": "shield",
    "shops": [
      {
        "shop": "Cassie's Shield Shop",
        "location": "Falador",
        "basePrice": 20,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1075,
    "name": "Bronze platelegs",
    "version": "",
    "slot": "legs",
    "shops": [
      {
        "shop": "Louie's Armoured Legs Bazaar",
        "location": "Al Kharid",
        "basePrice": 80,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1087,
    "name": "Bronze plateskirt",
    "version": "",
    "slot": "legs",
    "shops": [
      {
        "shop": "Ranael's Super Skirt Store",
        "location": "Al Kharid",
        "basePrice": 80,
        "stockBase": 5
      }
    ]
  },
  {
    "itemId": 1067,
    "name": "Iron platelegs",
    "version": "",
    "slot": "legs",
    "shops": [
      {
        "shop": "Horvik's Armour Shop",
        "location": "Varrock",
        "basePrice": 280,
        "stockBase": 1
      },
      {
        "shop": "Louie's Armoured Legs Bazaar",
        "location": "Al Kharid",
        "basePrice": 280,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1081,
    "name": "Iron plateskirt",
    "version": "",
    "slot": "legs",
    "shops": [
      {
        "shop": "Ranael's Super Skirt Store",
        "location": "Al Kharid",
        "basePrice": 280,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 428,
    "name": "Priest gown (bottom)",
    "version": "",
    "slot": "legs",
    "shops": [
      {
        "shop": "Thessalia's Fine Clothes",
        "location": "Varrock",
        "basePrice": 5,
        "stockBase": 3
      },
      {
        "shop": "Fancy Clothes Store",
        "location": "Varrock",
        "basePrice": 6,
        "stockBase": 3
      }
    ]
  },
  {
    "itemId": 1059,
    "name": "Leather gloves",
    "version": "",
    "slot": "hands",
    "shops": [
      {
        "shop": "Thessalia's Fine Clothes",
        "location": "Varrock",
        "basePrice": 6,
        "stockBase": 10
      },
      {
        "shop": "Fancy Clothes Store",
        "location": "Varrock",
        "basePrice": 7,
        "stockBase": 10
      }
    ]
  },
  {
    "itemId": 1061,
    "name": "Leather boots",
    "version": "",
    "slot": "feet",
    "shops": [
      {
        "shop": "Thessalia's Fine Clothes",
        "location": "Varrock",
        "basePrice": 6,
        "stockBase": 10
      },
      {
        "shop": "Fancy Clothes Store",
        "location": "Varrock",
        "basePrice": 7,
        "stockBase": 10
      }
    ]
  }
];
