#!/usr/bin/env node
// =============================================================================
// scripts/postinstall.mjs — apply local patches to node_modules after install
// =============================================================================
//
// Currently fixes a packaging bug in osrscachereader@github:Dezinater/...#ef3e0fe:
// RSCache.js imports `../allAnimNames.js` (a name lookup table generated by
// their `npm run generate` script), but that file is excluded from npm-pack
// in their .npmignore. The function that uses it (getAnimName) just returns
// `AnimNames[animId]` — we stub it as an empty object so the import resolves
// and `getAnimName` returns `undefined`. We don't need anim names yet.
//
// Idempotent — safe to run multiple times.
// =============================================================================

import { existsSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ANIM_STUB = join(ROOT, 'node_modules', 'osrscachereader', 'src', 'allAnimNames.js');

if (!existsSync(ANIM_STUB)) {
  writeFileSync(
    ANIM_STUB,
    '// Stub generated by scripts/postinstall.mjs — see that file for context.\nexport default {};\n',
  );
  process.stdout.write(`  patched: ${ANIM_STUB}\n`);
}
