#!/usr/bin/env node
// =============================================================================
// scripts/postinstall.mjs — apply local patches to node_modules after install
// =============================================================================
//
// Patches osrscachereader@github:Dezinater/osrscachereader#ef3e0fe:
//
// 1) Stub `src/allAnimNames.js`. RSCache.js imports it but it's excluded from
//    npm-pack. The function that uses it (getAnimName) just returns
//    `AnimNames[animId]` — we stub as `{}` so the import resolves and
//    getAnimName returns undefined. We don't need anim names yet.
//
// 2) Patch `ItemLoader.js`'s UNHANDLED-OPCODE warning to include `def.id` so
//    we can attribute warnings to specific items. Tooling like
//    scripts/find-bad-opcodes.mjs depends on this format.
//
// Idempotent — safe to run multiple times.
// =============================================================================

import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PKG = join(ROOT, 'node_modules', 'osrscachereader');

const log = (m) => process.stdout.write(`  ${m}\n`);

// --- patch 1: allAnimNames stub ---------------------------------------------
const ANIM_STUB = join(PKG, 'src', 'allAnimNames.js');
if (!existsSync(ANIM_STUB)) {
  writeFileSync(
    ANIM_STUB,
    '// Stub generated by scripts/postinstall.mjs — see that file for context.\nexport default {};\n',
  );
  log(`patched: ${ANIM_STUB}`);
}

// --- patch 2: ItemLoader warning includes def.id ----------------------------
const ITEM_LOADER = join(PKG, 'src', 'cacheReader', 'loaders', 'ItemLoader.js');
if (existsSync(ITEM_LOADER)) {
  const src = readFileSync(ITEM_LOADER, 'utf8');
  const before = '"UNHANDLED OPCODE [ItemLoader]: " + opcode + " last: " + lastOpCode';
  const after = '"UNHANDLED OPCODE [ItemLoader]: " + opcode + " last: " + lastOpCode + " item: " + def.id';
  if (src.includes(before) && !src.includes(after)) {
    writeFileSync(ITEM_LOADER, src.replace(before, after));
    log(`patched: ${ITEM_LOADER}`);
  }
}
